const SERVICE_NAME = 'IBERFIT Cloudflare API';
const SERVICE_VERSION = '2026-06-30-v10.0.1-master-stable-audit-fix';
const UPSTREAM_TIMEOUT_MS = 12000;
function jsonResponse(body,status=200,extraHeaders={}){return new Response(JSON.stringify(body,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...extraHeaders}})}
function corsHeaders(request,env){const origin=request.headers.get('Origin')||'';const configured=(env.IBERFIT_ALLOWED_ORIGINS||'https://app.iberfit.cl').split(',').map(x=>x.trim()).filter(Boolean);const allow=configured.includes('*')||configured.includes(origin)?(origin||configured[0]):configured[0];return {'access-control-allow-origin':allow,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type, authorization, x-iberfit-client','access-control-max-age':'86400',vary:'Origin'}}
function envStatus(env){return {upstreamConfigured:Boolean(env.APPS_SCRIPT_WEBAPP_URL),workerSecretConfigured:Boolean(env.IBERFIT_WORKER_SECRET),allowedOriginsConfigured:Boolean(env.IBERFIT_ALLOWED_ORIGINS)}}
function validateEnv(env){const missing=[];if(!env.APPS_SCRIPT_WEBAPP_URL)missing.push('APPS_SCRIPT_WEBAPP_URL');if(!env.IBERFIT_WORKER_SECRET)missing.push('IBERFIT_WORKER_SECRET');return missing}
async function readJson(request){const text=await request.text();if(!text.trim())return {};try{return JSON.parse(text)}catch{throw new Error('INVALID_JSON_BODY')}}
async function proxyToAppsScript(payload,env,request){const cors=corsHeaders(request,env);const missing=validateEnv(env);if(missing.length)return jsonResponse({ok:false,service:SERVICE_NAME,error:'CONFIG_ERROR',missing,env:envStatus(env)},500,cors);const requestId=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;const upstreamPayload={...payload,workerSecret:env.IBERFIT_WORKER_SECRET,_workerSecret:env.IBERFIT_WORKER_SECRET,_meta:{...(payload._meta||{}),requestId,source:'cloudflare-pages-function',service:SERVICE_NAME,version:SERVICE_VERSION,ts:new Date().toISOString()}};const controller=new AbortController();const timeoutId=setTimeout(()=>controller.abort('Apps Script timeout'),UPSTREAM_TIMEOUT_MS);let upstream;try{upstream=await fetch(env.APPS_SCRIPT_WEBAPP_URL,{method:'POST',redirect:'follow',headers:{'content-type':'application/json','x-iberfit-worker-secret':env.IBERFIT_WORKER_SECRET},body:JSON.stringify(upstreamPayload),signal:controller.signal})}catch(error){const isTimeout=String(error?.name||error).includes('Abort')||String(error).includes('timeout');return jsonResponse({ok:false,service:SERVICE_NAME,error:isTimeout?'UPSTREAM_TIMEOUT':'UPSTREAM_FETCH_FAILED',requestId,detail:String(error&&error.message?error.message:error)},isTimeout?504:502,cors)}finally{clearTimeout(timeoutId)}const text=await upstream.text();let data;try{data=text?JSON.parse(text):{}}catch{return jsonResponse({ok:false,service:SERVICE_NAME,error:'UPSTREAM_NON_JSON_RESPONSE',requestId,upstreamStatus:upstream.status,preview:text.slice(0,500)},502,cors)}return jsonResponse({ok:upstream.ok&&data.ok!==false,service:SERVICE_NAME,version:SERVICE_VERSION,requestId,upstreamStatus:upstream.status,data},upstream.ok?200:502,cors)}
export async function onRequest(context){const {request,env}=context;const cors=corsHeaders(request,env);const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(request.method==='GET'){const action=url.searchParams.get('action');if(!action||action==='health')return jsonResponse({ok:true,service:SERVICE_NAME,status:'ready',version:SERVICE_VERSION,...envStatus(env)},200,cors);return proxyToAppsScript({action,params:Object.fromEntries(url.searchParams.entries())},env,request)}if(request.method!=='POST')return jsonResponse({ok:false,service:SERVICE_NAME,error:'METHOD_NOT_ALLOWED'},405,{...cors,allow:'GET,POST,OPTIONS'});try{const payload=await readJson(request);if(!payload.action)payload.action='health';return proxyToAppsScript(payload,env,request)}catch(error){return jsonResponse({ok:false,service:SERVICE_NAME,error:String(error&&error.message?error.message:error)},400,cors)}}
