import { iberfitApi, saveClientSession, readClientSession, clearClientSession } from './api-v10.js';
import { IBERFIT_CONFIG } from './config-v10.js';

const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];
const state = { authed:false, active:'home', data:null, session:null, selectedSessionId:'' };

function esc(v=''){return String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function first(...vals){return vals.find(v=>String(v ?? '').trim()) ?? '';}
function key(v=''){return String(v||'').trim().toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function modality(v=''){const k=key(v); if(k.includes('PRESENCIAL'))return 'PRESENCIAL'; if(k.includes('ONLINE')||k.includes('REMOTO'))return 'ONLINE'; if(k.includes('HIBRIDO')||k.includes('HYBRID'))return 'HIBRIDO'; return 'PRESENCIAL';}
function modalityText(m){return {PRESENCIAL:'Modalidad Presencial · Entrenamiento guiado con seguimiento técnico',HIBRIDO:'Modalidad Híbrida · Sesión presencial + trabajo autónomo',ONLINE:'Modalidad Online · Planificación y seguimiento remoto'}[m]||'Modalidad IBERFIT';}
function clientFirstName(name='Cliente'){return String(name||'Cliente').trim().split(/\s+/)[0] || 'Cliente';}
function normalizePayload(payload={}){const raw=payload.data && !payload.client ? payload.data : payload; const c=raw.client||raw.cliente||{}; const client={id:first(c.id,c.clientId,c.CLIENTE_ID,raw.clientId), name:first(c.name,c.nombre,c.NOMBRE_VISIBLE,c.NOMBRE,'Cliente IBERFIT'), email:first(c.email,c.EMAIL), phone:first(c.phone,c.telefono,c.TELEFONO), modality:modality(first(c.modality,c.modalidad,c.MODALIDAD)), objective:first(c.objective,c.objetivo,c.OBJETIVO_PRINCIPAL,c.OBJETIVO,'Proceso IBERFIT'), status:first(c.status,c.estado,c.ESTADO)}; const week=raw.week||raw.semana||{}; const sessions=Array.isArray(week.sessions)?week.sessions:(Array.isArray(raw.sessions)?raw.sessions:[]); const iri=raw.iri||raw.diagnosticoIri||{}; const process=raw.process||raw.proceso||{}; const home=raw.home||{}; return {...raw,client,week:{...week,sessions},iri,process,home:{week:first(home.week,home.semana,week.title,week.titulo,sessions.length?'Semana publicada':'Pendiente de publicación'), iri:first(home.iri,iri.score,iri.total,iri.classification,'Diagnóstico pendiente'), sessions:first(home.sessions,home.sesiones,sessions.length?String(sessions.length):'Sin sesiones publicadas'), rpe:first(home.rpe,process.rpe,'Pendiente de primer registro'), focus:first(home.focus,home.foco,client.objective,'Revisar estado y próxima indicación IBERFIT.'), nextDecision:first(home.nextDecision,home.proximaDecision,'Registrar respuesta real para ajustar el proceso.')}};}
function showStatus(text,type='error'){const box=$('#statusBox'); if(!box)return; box.className='status-box '+(type==='ok'?'success-box':''); box.textContent=text; box.classList.remove('hidden');}
function hideStatus(){const box=$('#statusBox'); if(box) box.classList.add('hidden');}
function showLogin(){state.authed=false; $('#accessScreen')?.classList.remove('hidden'); $('#clientApp')?.classList.add('hidden'); const last=localStorage.getItem(IBERFIT_CONFIG.loginStorageKey); if(last && $('#login')) $('#login').value=last;}
function showApp(){state.authed=true; $('#accessScreen')?.classList.add('hidden'); $('#clientApp')?.classList.remove('hidden'); updateShell(); render();}
function updateShell(){const c=state.data?.client||{}; const m=modality(c.modality); $('#sidebarClientName').textContent=c.name||'Espacio cliente'; $('#sidebarModality').textContent=m; $('#modalityBadge').textContent=m; $('#modalityBadge').classList.remove('hidden'); $('#headerContext').textContent=screenTitle(state.active);}
function screenTitle(s){return {home:'Inicio',week:'Semana',session:'Sesión',process:'Proceso',channel:'Canal'}[s]||'Inicio';}
async function doLogin(ev){ev?.preventDefault(); hideStatus(); const login=$('#login')?.value.trim()||''; const password=$('#password')?.value||''; if(!login||!password){showStatus('Ingresa usuario y contraseña.');return;} localStorage.setItem(IBERFIT_CONFIG.loginStorageKey,login); showStatus('Conectando con IBERFIT...','ok'); const res=await iberfitApi('login',{login,password}); if(!res||res.ok===false){clearClientSession(); const msg=res?.status==='ACCESS_CLIENT_MISMATCH'?'IBERFIT detectó una inconsistencia de acceso. Contacta a IBERFIT para revisar tu cuenta.':(res?.message||res?.status||'No se pudo iniciar sesión.'); showStatus(msg); return;} const payload=normalizePayload(res.data||res); const resolvedEmail=String(payload.client.email||'').toLowerCase(); if(login.includes('@')&&resolvedEmail&&resolvedEmail!==login.toLowerCase()){clearClientSession(); showStatus('IBERFIT bloqueó una sesión con identidad cruzada. Contacta a IBERFIT.'); return;} state.session=saveClientSession({data:{...payload,sessionToken:(res.data||res).sessionToken,expiresAt:(res.data||res).expiresAt}}); state.data=payload; showApp();}
async function restore(){const s=readClientSession(); if(!s){showLogin();return;} state.session=s; const res=await iberfitApi('getHome',{sessionToken:s.sessionToken}); if(!res||res.ok===false){clearClientSession();showLogin();return;} const payload=normalizePayload(res.data||res); if(s.clientId && payload.client.id && s.clientId!==payload.client.id){clearClientSession();showLogin();showStatus('Sesión cerrada por seguridad: identidad no coincide.');return;} state.data=payload; showApp();}
function nav(screen){state.active=screen; updateShell(); render(); $$('.sidebar-btn,.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen));}
function homeScreen(){const d=state.data, c=d.client, h=d.home, m=modality(c.modality); return `<section class="hero-card"><p>ESPACIO PRIVADO IBERFIT</p><h1>Hola, ${esc(clientFirstName(c.name))}</h1><span>${esc(c.objective||'Tu proceso IBERFIT está activo.')}</span></section><div class="notice">${esc(modalityText(m))}</div><section class="grid-2"><article class="app-card"><h2>Qué hacer ahora</h2><p><strong>Foco:</strong> ${esc(h.focus)}</p><p><strong>Próxima decisión:</strong> ${esc(h.nextDecision)}</p><button class="btn btn-primary" data-go="week">Ver mi semana</button></article><article class="app-card"><h2>Método IBERFIT</h2><p>No entregamos una rutina suelta. Evaluamos, interpretamos, planificamos y ajustamos con criterio basado en tu respuesta real.</p></article></section><div class="screen-title">Tu semana en números</div><section class="metric-grid"><article class="app-card"><strong>${esc(h.week)}</strong><span>Semana</span></article><article class="app-card"><strong>${esc(h.iri)}</strong><span>IRI</span></article><article class="app-card"><strong>${esc(h.sessions)}</strong><span>Sesiones</span></article><article class="app-card"><strong>${esc(h.rpe)}</strong><span>RPE</span></article></section>`;}
function weekScreen(){const sessions=state.data.week.sessions||[]; return `<section class="hero-card"><p>SEMANA IBERFIT</p><h1>${esc(state.data.week.title||'Semana pendiente')}</h1><span>${esc(state.data.week.message||'Cuando Carlos publique tu semana, aparecerá aquí.')}</span></section><section class="session-list">${sessions.length?sessions.map(s=>`<article class="session-card"><span class="pill">${esc(s.type||s.delivery||'Sesión')}</span><h2>${esc(s.title||'Sesión IBERFIT')}</h2><p>${esc(s.objective||s.criterion||'Sesión publicada por IBERFIT.')}</p><div class="session-actions"><button class="btn btn-primary" data-session="${esc(s.id)}">Ver sesión</button></div></article>`).join(''):`<article class="app-card"><h2>Sin sesiones publicadas</h2><p>Tu espacio ya está activo. La semana aparecerá cuando Coach OS publique contenido para ti.</p></article>`}</section>`;}
function sessionScreen(){const sessions=state.data.week.sessions||[]; const s=sessions.find(x=>String(x.id)===String(state.selectedSessionId))||sessions[0]; if(!s)return `<article class="app-card"><h2>Sesión pendiente</h2><p>Sin sesión publicada todavía.</p></article>`; const blocks=Array.isArray(s.blocks)?s.blocks:[]; return `<section class="hero-card"><p>SESIÓN IBERFIT</p><h1>${esc(s.title||'Sesión')}</h1><span>${esc(s.objective||'Entrena según indicación IBERFIT.')}</span></section>${blocks.length?blocks.map(b=>`<article class="app-card"><h2>${esc(b.title||'Bloque')}</h2><ul>${(b.exercises||[]).map(e=>`<li><strong>${esc(e.name||'Ejercicio')}</strong> ${esc([e.sets,e.reps||e.time,e.load].filter(Boolean).join(' · '))}</li>`).join('')}</ul></article>`).join(''):`<article class="app-card"><h2>Estructura</h2><p class="preline">${esc(s.structure||'Sin estructura detallada publicada.')}</p></article>`}<article class="app-card"><h2>Feedback rápido</h2><div class="form-grid"><div class="field"><label>RPE 1–10</label><input id="fbRpe" type="number" min="1" max="10"></div><div class="field"><label>Molestia 1–10</label><input id="fbPain" type="number" min="1" max="10"></div></div><div class="field"><label>Comentario</label><textarea id="fbText"></textarea></div><button class="btn btn-primary" id="sendFeedback">Enviar feedback</button><div id="feedbackStatus"></div></article>`;}
function processScreen(){const iri=state.data.iri||{}; return `<section class="hero-card"><p>PROCESO</p><h1>Progresión medible</h1><span>Tu evolución se interpreta por tendencia, no por datos aislados.</span></section><section class="metric-grid"><article class="app-card"><strong>${esc(iri.score||iri.total||'Pendiente')}</strong><span>IRI</span></article><article class="app-card"><strong>${esc(iri.classification||iri.clasificacion||'Diagnóstico')}</strong><span>Clasificación</span></article><article class="app-card"><strong>${esc(state.data.home.rpe)}</strong><span>RPE</span></article><article class="app-card"><strong>${esc(state.data.client.modality)}</strong><span>Modalidad</span></article></section><article class="app-card"><h2>Check-in semanal</h2><div class="form-grid"><div class="field"><label>Sueño 1–10</label><input id="chkSleep" type="number" min="1" max="10"></div><div class="field"><label>Energía 1–10</label><input id="chkEnergy" type="number" min="1" max="10"></div><div class="field"><label>Fatiga 1–10</label><input id="chkFatigue" type="number" min="1" max="10"></div><div class="field"><label>Motivación 1–10</label><input id="chkMotivation" type="number" min="1" max="10"></div></div><div class="field"><label>Comentario</label><textarea id="chkText"></textarea></div><button class="btn btn-primary" id="sendCheckin">Enviar check-in</button><div id="checkinStatus"></div></article>`;}
function channelScreen(){const msg=encodeURIComponent('Hola IBERFIT, escribo desde mi espacio privado.'); return `<section class="hero-card"><p>CANAL DIRECTO</p><h1>Comunicación IBERFIT</h1><span>Usa este canal para reportar contexto relevante, molestias o dudas.</span></section><article class="app-card"><h2>WhatsApp</h2><p>La app no sustituye el criterio humano. Reporta cualquier cambio importante para ajustar el proceso.</p><a class="btn btn-primary" target="_blank" rel="noopener" href="https://wa.me/${IBERFIT_CONFIG.whatsappNumber}?text=${msg}">Abrir WhatsApp</a></article>`;}
function render(){const root=$('#screenContainer'); if(!root)return; const map={home:homeScreen,week:weekScreen,session:sessionScreen,process:processScreen,channel:channelScreen}; root.innerHTML=(map[state.active]||homeScreen)(); root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go)); root.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{state.selectedSessionId=b.dataset.session;nav('session')}); const fb=$('#sendFeedback'); if(fb)fb.onclick=sendFeedback; const chk=$('#sendCheckin'); if(chk)chk.onclick=sendCheckin;}
async function sendFeedback(){const s=state.data.week.sessions[0]||{}; const res=await iberfitApi('submitFeedback',{sessionToken:state.session.sessionToken,sessionId:s.id||'',rpe:$('#fbRpe')?.value,pain:$('#fbPain')?.value,comment:$('#fbText')?.value}); $('#feedbackStatus').innerHTML=res.ok!==false?'<div class="status-box success-box">Feedback guardado.</div>':'<div class="status-box">No se pudo guardar.</div>';}
async function sendCheckin(){const res=await iberfitApi('submitCheckin',{sessionToken:state.session.sessionToken,sleep:$('#chkSleep')?.value,energy:$('#chkEnergy')?.value,fatigue:$('#chkFatigue')?.value,motivation:$('#chkMotivation')?.value,comment:$('#chkText')?.value}); $('#checkinStatus').innerHTML=res.ok!==false?'<div class="status-box success-box">Check-in guardado.</div>':'<div class="status-box">No se pudo guardar.</div>';}
function boot(){ $('#loginForm')?.addEventListener('submit',doLogin); $('#connectionCheckBtn')?.addEventListener('click',async()=>{const r=await iberfitApi('backendHealth',{}); showStatus(r.ok!==false?'Conexión activa con IBERFIT.':(r.message||r.status||'No se pudo verificar.'),r.ok!==false?'ok':'error');}); $('#helpBtn')?.addEventListener('click',()=>{window.open(`https://wa.me/${IBERFIT_CONFIG.whatsappNumber}?text=${encodeURIComponent('Hola IBERFIT, necesito ayuda con mi acceso.')}`,'_blank')}); [...document.querySelectorAll('[data-screen]')].forEach(b=>b.addEventListener('click',()=>nav(b.dataset.screen))); restore();}
window.addEventListener('error',ev=>console.error('IBERFIT client error',ev));
boot();
