import { iberfitApi, saveClientSession, readClientSession, clearClientSession } from './api-v10.js';
import { IBERFIT_CONFIG } from './config-v10.js';

const state = { session: null, data: null, active: 'home', selectedSessionId: '' };
const SCREENS = { home: 'Inicio', week: 'Semana', session: 'Sesión', process: 'Proceso', channel: 'Canal' };
function $(q, root = document) { return root.querySelector(q); }
function $$(q, root = document) { return Array.from(root.querySelectorAll(q)); }
function esc(v = '') { return String(v ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
function arr(v) { return Array.isArray(v) ? v : []; }
function valueOf(...values) { return values.find(v => v !== undefined && v !== null && String(v).trim() !== '') ?? ''; }
function firstName(name = '') { return String(name || 'cliente').trim().split(/\s+/)[0] || 'cliente'; }
function modality(raw = '') { const v = String(raw || 'PRESENCIAL').toUpperCase(); if (v.includes('HIB')) return 'Híbrida'; if (v.includes('ONLINE')) return 'Online'; return 'Presencial'; }
function modalityText(m) { if (m === 'Presencial') return 'Modalidad presencial. La técnica, carga y progresión se trabajan con seguimiento directo IBERFIT.'; if (m === 'Online') return 'Modalidad online. Tu proceso se sostiene con planificación, reporte y ajustes según respuesta.'; return 'Modalidad híbrida. Integra sesiones presenciales y trabajo autónomo con seguimiento.'; }
function showStatus(message, type = 'error') { const box = $('#statusBox'); if (!box) return; box.textContent = message; box.className = `status-box ${type === 'ok' ? 'success-box' : ''}`; }
function hideStatus() { $('#statusBox')?.classList.add('hidden'); }
function normalizeClient(raw = {}) { return { id: valueOf(raw.id, raw.CLIENTE_ID, raw.clientId), name: valueOf(raw.name, raw.NOMBRE_VISIBLE, raw.nombre, 'cliente'), email: valueOf(raw.email, raw.EMAIL, ''), modality: valueOf(raw.modality, raw.MODALIDAD, 'PRESENCIAL'), objective: valueOf(raw.objective, raw.OBJETIVO_PRINCIPAL, raw.objetivo, 'Proceso IBERFIT'), status: valueOf(raw.status, raw.ESTADO, '') }; }
function normalizePayload(raw = {}) {
  const client = normalizeClient(raw.client || raw.cliente || raw);
  const weekRaw = raw.week || raw.semana || {};
  const sessions = arr(weekRaw.sessions || weekRaw.sesiones || raw.sessions || raw.sesiones).map(normalizeSession);
  const iri = raw.iri || raw.diagnosticoIri || raw.diagnostico || {};
  const reports = arr(raw.reports || raw.informes);
  const home = raw.home || {};
  return { client, week: { title: valueOf(weekRaw.title, weekRaw.TITULO_SEMANA, 'Semana pendiente de publicación'), message: valueOf(weekRaw.message, weekRaw.MENSAJE_IBERFIT, 'Cuando Coach OS publique tu semana, aparecerá aquí.'), sessions }, iri, reports, home: { focus: valueOf(home.focus, client.objective, 'Proceso activo'), nextDecision: valueOf(home.nextDecision, 'Esperar publicación o indicación IBERFIT'), week: valueOf(home.week, sessions.length ? 'Publicada' : 'Pendiente'), iri: valueOf(home.iri, iri.score, iri.total, iri.IRI_TOTAL, 'Diagnóstico pendiente'), sessions: valueOf(home.sessions, sessions.length ? String(sessions.length) : 'Sin sesiones publicadas'), rpe: valueOf(home.rpe, 'Pendiente') }, raw };
}
function normalizeSession(s = {}) { return { ...s, id: valueOf(s.id, s.SESION_ID), title: valueOf(s.title, s.TITULO_SESION, 'Sesión IBERFIT'), type: valueOf(s.type, s.TIPO_SESION, s.MODALIDAD_SESION, 'Sesión'), objective: valueOf(s.objective, s.OBJETIVO_SESION, s.criterion, s.CRITERIO_COACH, ''), structure: valueOf(s.structure, s.ESTRUCTURA_SESION, s.BLOQUE_PRINCIPAL, ''), status: valueOf(s.status, s.ESTADO_SESION, ''), blocks: arr(s.blocks || s.bloques) }; }
function showLogin() { $('#accessScreen')?.classList.remove('hidden'); $('#clientApp')?.classList.add('hidden'); const last = localStorage.getItem(IBERFIT_CONFIG.loginStorageKey); if (last && $('#login')) $('#login').value = last; }
function showApp() { $('#accessScreen')?.classList.add('hidden'); $('#clientApp')?.classList.remove('hidden'); updateShell(); render(); }
function updateShell() { const c = state.data?.client || {}; const m = modality(c.modality); $('#sidebarClientName').textContent = c.name || 'Espacio cliente'; $('#sidebarModality').textContent = m; $('#modalityBadge').textContent = m; $('#modalityBadge').classList.remove('hidden'); $('#headerContext').textContent = SCREENS[state.active] || 'Inicio'; }
async function doLogin(event) { event?.preventDefault(); hideStatus(); const login = $('#login')?.value.trim() || ''; const password = $('#password')?.value || ''; if (!login || !password) { showStatus('Ingresa usuario y contraseña.'); return; } localStorage.setItem(IBERFIT_CONFIG.loginStorageKey, login); showStatus('Conectando con IBERFIT...', 'ok'); const res = await iberfitApi('login', { login, password }); if (!res || res.ok === false) { clearClientSession(); const msg = res?.status === 'ACCESS_CLIENT_MISMATCH' ? 'IBERFIT detectó una inconsistencia de acceso. Contacta a IBERFIT para revisar tu cuenta.' : (res?.message || res?.status || 'No se pudo iniciar sesión.'); showStatus(msg); return; } const payload = normalizePayload(res.data || res); const resolvedEmail = String(payload.client.email || '').toLowerCase(); if (login.includes('@') && resolvedEmail && resolvedEmail !== login.toLowerCase()) { clearClientSession(); showStatus('IBERFIT bloqueó una sesión con identidad cruzada. Contacta a IBERFIT.'); return; } try { state.session = saveClientSession({ data: { ...(res.data || res), client: payload.client } }); } catch (err) { showStatus(`El acceso respondió incompleto: ${err.message}`); return; } state.data = payload; showApp(); }
async function restore() { const s = readClientSession(); if (!s) { showLogin(); return; } state.session = s; const res = await iberfitApi('getHome', { sessionToken: s.sessionToken }); if (!res || res.ok === false) { clearClientSession(); showLogin(); showStatus(res?.message || res?.status || 'Sesión vencida.'); return; } const payload = normalizePayload(res.data || res); if (s.clientId && payload.client.id && s.clientId !== payload.client.id) { clearClientSession(); showLogin(); showStatus('Sesión cerrada por seguridad: identidad no coincide.'); return; } state.data = payload; showApp(); }
function nav(screen) { state.active = screen; updateShell(); render(); $$('.sidebar-btn,.nav-btn').forEach(b => b.classList.toggle('active', b.dataset.screen === screen)); }
function homeScreen() { const d = state.data, c = d.client, h = d.home, m = modality(c.modality); return `<section class="hero-card"><p>ESPACIO PRIVADO IBERFIT</p><h1>Hola, ${esc(firstName(c.name))}</h1><span>${esc(c.objective || 'Tu proceso IBERFIT está activo.')}</span></section><div class="notice">${esc(modalityText(m))}</div><section class="grid-2"><article class="app-card"><h2>Qué estamos priorizando</h2><p><strong>Foco:</strong> ${esc(h.focus)}</p><p><strong>Próxima decisión:</strong> ${esc(h.nextDecision)}</p><p>IBERFIT no entrega una rutina aislada: interpreta tu respuesta y ajusta la progresión.</p><button class="btn btn-primary" data-go="week">Ver mi semana</button></article><article class="app-card"><h2>Criterio de la sesión</h2><p>Antes de subir carga o complejidad revisamos técnica, RPE, molestias, descanso y adherencia. La progresión se decide con datos y criterio.</p></article></section><div class="screen-title">Resumen del proceso</div><section class="metric-grid"><article class="app-card"><strong class="metric">${esc(h.week)}</strong><span class="label">Semana</span></article><article class="app-card"><strong class="metric">${esc(h.iri)}</strong><span class="label">IRI</span></article><article class="app-card"><strong class="metric">${esc(h.sessions)}</strong><span class="label">Sesiones</span></article><article class="app-card"><strong class="metric">${esc(h.rpe)}</strong><span class="label">RPE</span></article></section>`; }
function weekScreen() { const sessions = state.data.week.sessions || []; return `<section class="hero-card"><p>SEMANA IBERFIT</p><h1>${esc(state.data.week.title)}</h1><span>${esc(state.data.week.message)}</span></section><section class="session-list">${sessions.length ? sessions.map(s => `<article class="session-card"><span class="pill">${esc(s.type)}</span><h2>${esc(s.title)}</h2><p>${esc(s.objective || 'Sesión publicada por IBERFIT.')}</p><div class="session-actions"><button class="btn btn-primary" data-session="${esc(s.id)}">Ver sesión</button></div></article>`).join('') : `<article class="app-card"><h2>Sin sesiones publicadas</h2><p>Tu espacio está activo. La semana aparecerá cuando Coach OS publique contenido para ti.</p></article>`}</section>`; }
function sessionScreen() { const sessions = state.data.week.sessions || []; const s = sessions.find(x => String(x.id) === String(state.selectedSessionId)) || sessions[0]; if (!s) return `<article class="app-card"><h2>Sesión pendiente</h2><p>Sin sesión publicada todavía.</p></article>`; const blocks = arr(s.blocks); return `<section class="hero-card"><p>SESIÓN IBERFIT</p><h1>${esc(s.title)}</h1><span>${esc(s.objective || 'Entrena según indicación IBERFIT.')}</span></section>${blocks.length ? blocks.map(b => `<article class="app-card"><h2>${esc(b.title || 'Bloque')}</h2><ul>${arr(b.exercises || b.ejercicios).map(e => `<li><strong>${esc(e.name || e.nombre || 'Ejercicio')}</strong> ${esc([e.sets || e.series, e.reps || e.time || e.tiempo, e.load || e.carga].filter(Boolean).join(' · '))}</li>`).join('')}</ul></article>`).join('') : `<article class="app-card"><h2>Estructura</h2><p class="preline">${esc(s.structure || 'Sin estructura detallada publicada.')}</p></article>`}<article class="app-card"><h2>Feedback rápido</h2><div class="form-grid"><div class="field"><label>RPE 1–10</label><input id="fbRpe" type="number" min="1" max="10"></div><div class="field"><label>Molestia 0–10</label><input id="fbPain" type="number" min="0" max="10"></div></div><div class="field"><label>Comentario</label><textarea id="fbText" placeholder="Qué sentiste, qué fue difícil, qué molestó, qué salió bien..."></textarea></div><button class="btn btn-primary" id="sendFeedback">Enviar feedback</button><div id="feedbackStatus"></div></article>`; }
function processScreen() { const iri = state.data.iri || {}; const total = valueOf(iri.score, iri.total, iri.IRI_TOTAL, 'Pendiente'); const classification = valueOf(iri.classification, iri.clasificacion, iri.CLASIFICACION, 'Diagnóstico'); const reports = arr(state.data.reports); return `<section class="hero-card"><p>PROCESO</p><h1>Progresión medible</h1><span>Tu evolución se interpreta por tendencia, no por datos aislados.</span></section><section class="metric-grid"><article class="app-card"><strong class="metric">${esc(total)}</strong><span class="label">IRI</span></article><article class="app-card"><strong class="metric">${esc(classification)}</strong><span class="label">Clasificación</span></article><article class="app-card"><strong class="metric">${esc(state.data.home.rpe)}</strong><span class="label">RPE</span></article><article class="app-card"><strong class="metric">${esc(modality(state.data.client.modality))}</strong><span class="label">Modalidad</span></article></section><section class="grid-2"><article class="app-card"><h2>Informe IRI</h2><p>${esc(valueOf(iri.recommendation, iri.RECOMENDACION, iri.DECISION_IBERFIT, 'Pendiente de publicación.'))}</p><pre class="qa-panel debug-panel">${esc(JSON.stringify(iri, null, 2))}</pre></article><article class="app-card"><h2>Informes publicados</h2>${reports.length ? reports.map(r => `<p><strong>${esc(valueOf(r.tipo, r.TIPO_INFORME, 'Informe'))}</strong><br>${esc(valueOf(r.resumen, r.RESUMEN, r.estado, r.ESTADO, 'Disponible'))}</p>`).join('') : '<p>Sin informes publicados todavía.</p>'}</article></section><article class="app-card"><h2>Check-in semanal</h2><div class="form-grid"><div class="field"><label>Sueño 1–10</label><input id="chkSleep" type="number" min="1" max="10"></div><div class="field"><label>Energía 1–10</label><input id="chkEnergy" type="number" min="1" max="10"></div><div class="field"><label>Fatiga 1–10</label><input id="chkFatigue" type="number" min="1" max="10"></div><div class="field"><label>Motivación 1–10</label><input id="chkMotivation" type="number" min="1" max="10"></div></div><div class="field"><label>Comentario</label><textarea id="chkText"></textarea></div><button class="btn btn-primary" id="sendCheckin">Enviar check-in</button><div id="checkinStatus"></div></article>`; }
function channelScreen() { const msg = encodeURIComponent('Hola IBERFIT, escribo desde mi espacio privado.'); return `<section class="hero-card"><p>CANAL DIRECTO</p><h1>Comunicación IBERFIT</h1><span>Usa este canal para reportar contexto relevante, molestias o dudas.</span></section><article class="app-card"><h2>WhatsApp</h2><p>La app no sustituye el criterio humano. Reporta cualquier cambio importante para ajustar el proceso.</p><a class="btn btn-primary" target="_blank" rel="noopener" href="https://wa.me/${IBERFIT_CONFIG.whatsappNumber}?text=${msg}">Abrir WhatsApp</a></article><article class="app-card"><h2>Privacidad</h2><p>Tu información se usa para seguimiento del proceso IBERFIT. No compartas claves ni datos sensibles por canales no oficiales.</p></article>`; }
function render() { const root = $('#screenContainer'); if (!root) return; const map = { home: homeScreen, week: weekScreen, session: sessionScreen, process: processScreen, channel: channelScreen }; root.innerHTML = (map[state.active] || homeScreen)(); root.querySelectorAll('[data-go]').forEach(b => b.addEventListener('click', () => nav(b.dataset.go))); root.querySelectorAll('[data-session]').forEach(b => b.addEventListener('click', () => { state.selectedSessionId = b.dataset.session; nav('session'); })); $('#sendFeedback')?.addEventListener('click', sendFeedback); $('#sendCheckin')?.addEventListener('click', sendCheckin); }
function selectedSession() { const sessions = state.data?.week?.sessions || []; return sessions.find(x => String(x.id) === String(state.selectedSessionId)) || sessions[0] || {}; }
async function sendFeedback() { const s = selectedSession(); const res = await iberfitApi('submitFeedback', { sessionToken: state.session.sessionToken, sessionId: s.id || '', rpe: $('#fbRpe')?.value, pain: $('#fbPain')?.value, comment: $('#fbText')?.value }); $('#feedbackStatus').innerHTML = res.ok !== false ? '<div class="status-box success-box">Feedback guardado en la sesión seleccionada.</div>' : `<div class="status-box">${esc(res.message || res.status || 'No se pudo guardar.')}</div>`; }
async function sendCheckin() { const res = await iberfitApi('submitCheckin', { sessionToken: state.session.sessionToken, sleep: $('#chkSleep')?.value, energy: $('#chkEnergy')?.value, fatigue: $('#chkFatigue')?.value, motivation: $('#chkMotivation')?.value, comment: $('#chkText')?.value }); $('#checkinStatus').innerHTML = res.ok !== false ? '<div class="status-box success-box">Check-in guardado.</div>' : `<div class="status-box">${esc(res.message || res.status || 'No se pudo guardar.')}</div>`; }
function boot() { $('#loginForm')?.addEventListener('submit', doLogin); $('#connectionCheckBtn')?.addEventListener('click', async () => { const r = await iberfitApi('backendHealth', {}); showStatus(r.ok !== false ? 'Conexión activa con IBERFIT.' : (r.message || r.status || 'No se pudo verificar.'), r.ok !== false ? 'ok' : 'error'); }); $('#helpBtn')?.addEventListener('click', () => { window.open(`https://wa.me/${IBERFIT_CONFIG.whatsappNumber}?text=${encodeURIComponent('Hola IBERFIT, necesito ayuda con mi acceso.')}`, '_blank'); }); $$('[data-screen]').forEach(b => b.addEventListener('click', () => nav(b.dataset.screen))); restore(); }
window.addEventListener('error', ev => { console.error('IBERFIT client error', ev.error || ev.message); const root = $('#screenContainer'); if (root) root.innerHTML = `<section class="app-card"><h2>Error de app</h2><p>${esc(ev.message || 'Error no especificado')}</p></section>`; });
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once: true }); else boot();
