import { iberfitApi, saveCoachSession, readCoachSession, clearCoachSession } from './api-v10.js';
const $=(q,root=document)=>root.querySelector(q); const $$=(q,root=document)=>[...root.querySelectorAll(q)];
const state={session:null,dashboard:null,clientId:'',workspace:null};
function esc(v=''){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function set(html){const root=$('#coachRoot'); if(root)root.innerHTML=html;}
function errorPage(title,msg,extra=''){set(`<main class="error-page"><section class="error-card"><h1>${esc(title)}</h1><p>${esc(msg)}</p>${extra?`<pre>${esc(extra)}</pre>`:''}<button class="btn btn-primary" id="reload">Recargar</button><button class="btn btn-ghost" id="api">Probar API</button></section></main>`); $('#reload').onclick=()=>location.href='/coach.html?v=10-'+Date.now(); $('#api').onclick=()=>window.open('/api/ibf','_blank');}
function login(message=''){clearCoachSession(); set(`<main class="coach-login-screen"><section class="coach-login-brand"><div class="coach-logo"><img src="/assets/iberfit-isotipo.png" alt="IBERFIT"></div><h1>IBERFIT Coach OS</h1><p>Diagnóstico, planificación, control de carga, seguimiento y publicación al cliente.</p><div class="coach-login-points"><span>V10.0.1</span><span>Canonical</span><span>QA</span><span>IA controlada</span></div></section><section class="coach-login-card"><h2>Acceso Coach OS</h2>${message?`<div class="form-error">${esc(message)}</div>`:''}<form id="coachLoginForm"><div class="field"><label>Usuario</label><input id="coachLogin" type="email" autocomplete="username" value="iberfit.cl@gmail.com"></div><div class="field"><label>Contraseña</label><input id="coachPassword" type="password" autocomplete="current-password"></div><button class="btn btn-primary btn-full" type="submit">Entrar a Coach OS</button></form><button class="btn btn-ghost btn-full" id="probe" style="margin-top:12px">Verificar backend</button><p class="muted">Ruta estable: /coach.html · API: /api/ibf</p></section></main>`); $('#coachLoginForm').onsubmit=doLogin; $('#probe').onclick=probe;}
async function probe(){const r=await iberfitApi('backendHealth',{}); errorPage('Backend Health',r.ok!==false?'Conexión correcta':'Backend con error',JSON.stringify(r,null,2));}
async function doLogin(ev){ev.preventDefault(); set(`<main class="error-page"><section class="error-card"><h1>Validando acceso</h1><p>Conectando con IBERFIT...</p></section></main>`); const r=await iberfitApi('coachLogin',{login:$('#coachLogin').value.trim(),password:$('#coachPassword').value}); if(!r||r.ok===false){login(r?.message||r?.status||'No se pudo iniciar sesión Coach.');return;} state.session=saveCoachSession(r); await loadDashboard();}
function shell(body){set(`<main class="coach-shell"><aside class="client-sidebar"><div><div class="brand-mini"><img src="/assets/iberfit-isotipo.png" alt="IBERFIT"><strong>IBERFIT</strong><span>Coach OS V10.0.1</span></div><nav class="client-nav"><button class="active" data-tab="dashboard">Dashboard</button><button data-tab="clients">Clientes</button><button data-tab="builder">Crear sesión</button><button data-tab="qa">QA Sistema</button><button id="logout">Salir</button></nav></div><div class="sidebar-footer">MASTER STABLE</div></aside><section class="client-main">${body}</section></main>`); $('#logout').onclick=()=>{clearCoachSession();login('Sesión cerrada.')}; $$('[data-tab]').forEach(b=>b.onclick=()=>renderTab(b.dataset.tab));}
async function loadDashboard(){const r=await iberfitApi('coachGetDashboard',{coachToken:state.session.coachToken}); if(!r||r.ok===false){login(r?.message||r?.status||'Sesión Coach caducada.');return;} state.dashboard=r.data||r; renderTab('dashboard');}
function renderTab(tab){const d=state.dashboard||{}; const clients=d.clients||[]; if(tab==='dashboard'){shell(`<div class="hero-card"><p>COACH OS V10.0.1</p><h1>Hola, ${esc(state.session?.coachName||'Coach IBERFIT')}</h1><span>Sistema estable: cliente, carga, sesiones, IRI, publicación y QA.</span></div>${metrics(d.metrics||{})}<section class="grid-2"><article class="app-card"><h2>Prioridad hoy</h2><p><strong>1.</strong> Verificar clientes activos.</p><p><strong>2.</strong> Crear/publicar sesiones solo con criterio completo.</p><p><strong>3.</strong> Revisar feedback y check-in antes de progresar cargas.</p></article><article class="app-card"><h2>Criterio IBERFIT</h2><p>Objetivo · qué observar · cómo ajustar · qué reportar. Sin este bloque, no se publica al cliente.</p></article></section>`);} else if(tab==='clients'){shell(`<div class="hero-card"><p>CLIENTES</p><h1>Gestión técnica</h1><span>Selecciona un cliente para ficha, IRI, cargas e histórico.</span></div><section class="app-card"><h2>Clientes activos</h2>${clients.map(clientButton).join('')||'<p>Sin clientes recibidos.</p>'}</section><section id="workspace" class="app-card"><h2>Workspace</h2><p>Selecciona un cliente.</p></section>`); bindClientButtons();} else if(tab==='builder'){shell(builderHtml()); bindBuilder();} else if(tab==='qa'){shell(qaHtml()); bindQa();}}
function metrics(m){return `<section class="metric-grid"><article class="app-card"><strong>${esc(m.clientes??'-')}</strong><span>Clientes</span></article><article class="app-card"><strong>${esc(m.sesionesPublicadas??'-')}</strong><span>Sesiones publicadas</span></article><article class="app-card"><strong>${esc(m.cargasRegistradas??'-')}</strong><span>Cargas</span></article><article class="app-card"><strong>${esc(m.alertas??'-')}</strong><span>Alertas</span></article></section>`;}
function clientButton(c){return `<button class="client-row" data-client="${esc(c.id)}"><strong>${esc(c.name||c.id)}</strong><span>${esc(c.modality||'')} · ${esc(c.objective||'')} · ${esc(c.status||'')}</span></button>`;}
function bindClientButtons(){ $$('[data-client]').forEach(b=>b.onclick=()=>loadClient(b.dataset.client)); }
async function loadClient(id){state.clientId=id; const ws=$('#workspace'); ws.innerHTML='<h2>Cargando...</h2>'; const r=await iberfitApi('coachGetClientWorkspace',{coachToken:state.session.coachToken,clientId:id}); if(!r||r.ok===false){ws.innerHTML=`<h2>Error</h2><p>${esc(r?.message||r?.status||'No se pudo cargar.')}</p><pre>${esc(JSON.stringify(r,null,2))}</pre>`;return;} state.workspace=r.data||r; const c=state.workspace.client||{}; const iri=state.workspace.iri||{}; const sessions=state.workspace.sessions||[]; const loads=state.workspace.loads||state.workspace.loadHistory||[]; ws.innerHTML=`<h2>${esc(c.name||c.id)}</h2><p><strong>Modalidad:</strong> ${esc(c.modality||'-')} · <strong>Objetivo:</strong> ${esc(c.objective||'-')}</p><p><strong>Acceso:</strong> ${esc(c.accessStatus||'-')} · <strong>Estado:</strong> ${esc(c.status||'-')}</p><section class="metric-grid"><article class="app-card"><strong>${esc(iri.score||iri.total||'-')}</strong><span>IRI</span></article><article class="app-card"><strong>${sessions.length}</strong><span>Sesiones</span></article><article class="app-card"><strong>${loads.length}</strong><span>Cargas</span></article><article class="app-card"><strong>${esc(c.modality||'-')}</strong><span>Modalidad</span></article></section><h3>Últimas sesiones</h3>${table(['Título','Estado','Fecha'],sessions.slice(0,8).map(s=>[s.title||s.TITULO_SESION,s.status||s.ESTADO_SESION,s.publishedAt||s.PUBLICADO_EN||s.updatedAt||s.ACTUALIZADO_EN]))}`;}
function table(headers, rows){return `<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v||'-')}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">Sin datos.</td></tr>`}</tbody></table>`;}
function builderHtml(){const clients=(state.dashboard?.clients||[]); return `<div class="hero-card"><p>CREAR SESIÓN</p><h1>Planificación con criterio</h1><span>Genera, edita, guarda borrador y publica solo cuando esté completo.</span></div><section class="app-card"><div class="form-grid"><div class="field"><label>Cliente</label><select id="bClient">${clients.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} · ${esc(c.modality||'')}</option>`).join('')}</select></div><div class="field"><label>Tipo</label><select id="bType"><option>PRESENCIAL</option><option>ONLINE</option><option>HIBRIDO</option></select></div></div><div class="field"><label>Objetivo sesión</label><input id="bObjective" placeholder="Ej: técnica de fuerza + control metabólico"></div><div class="field"><label>Criterio Coach</label><textarea id="bCriterion" placeholder="Hoy priorizamos... Qué observar... Cómo ajustar... Qué reportar..."></textarea></div><button class="btn btn-primary" id="aiSession">Crear sesión con IA controlada</button><button class="btn btn-ghost" id="saveDraft">Guardar borrador</button><div id="builderStatus"></div></section><section id="sessionDraft" class="app-card"><h2>Borrador</h2><p>Usa IA o escribe criterio manual.</p></section>`;}
function bindBuilder(){ $('#aiSession').onclick=async()=>{const r=await iberfitApi('coachAiGenerate',{coachToken:state.session.coachToken,mode:'SESSION_FULL',clientId:$('#bClient').value,objective:$('#bObjective').value,type:$('#bType').value}); const data=r.data||r; $('#sessionDraft').innerHTML=`<h2>${esc(data.title||'Sesión IBERFIT')}</h2><p><strong>Criterio:</strong> ${esc(data.criterion||'')}</p><pre class="qa-panel">${esc(JSON.stringify(data,null,2))}</pre>`; $('#bCriterion').value=data.criterion||$('#bCriterion').value; }; $('#saveDraft').onclick=async()=>{const r=await iberfitApi('coachSaveSessionDraft',{coachToken:state.session.coachToken,clientId:$('#bClient').value,type:$('#bType').value,objective:$('#bObjective').value,criterion:$('#bCriterion').value}); $('#builderStatus').innerHTML=r.ok!==false?'<div class="status-box success-box">Borrador guardado.</div>':`<div class="status-box">${esc(r.message||r.status||'Error')}</div>`;}; }
function qaHtml(){return `<div class="hero-card"><p>QA SISTEMA</p><h1>Verificación V10.0.1</h1><span>Confirma API, backend, canonical, migración e identidad.</span></div><section class="app-card"><button class="btn btn-primary" id="runQa">Ejecutar auditoría backend</button><pre id="qaOut" class="qa-panel" style="margin-top:14px">Pendiente.</pre></section>`;}
function bindQa(){ $('#runQa').onclick=async()=>{const r=await iberfitApi('adminV10SystemAudit',{coachToken:state.session?.coachToken}); $('#qaOut').textContent=JSON.stringify(r,null,2);};}
async function boot(){window.addEventListener('error',ev=>errorPage('Error Coach OS',ev.message,(ev.error&&ev.error.stack)||'')); window.addEventListener('unhandledrejection',ev=>errorPage('Promesa rechazada Coach OS',ev.reason?.message||String(ev.reason||''),ev.reason?.stack||'')); const s=readCoachSession(); if(!s){login();return;} state.session=s; await loadDashboard();}
boot();
